FROM trinodb/trino:400

# Cambiamos a root para crear directorios y asignar permisos
USER root

# Creamos el directorio para el plugin de Hive (usado para Hudi) y asignamos permisos
RUN mkdir -p /var/trino/var && chown -R trino:trino /var/trino

# Regresamos al usuario 'trino'
USER trino
