version: '3.8'

services:
  # Servicio MinIO
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./config/minio:/data
    command: server /data --console-address ":9001"

  # Servicio Spark Master
  spark-master:
    image: bitnami/spark:3.3.0
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8081:8080"
    environment:
      - SPARK_MODE=master
    networks:
      - spark-network

  # Servicio Spark Worker
  spark-worker:
    image: bitnami/spark:3.3.0
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - spark-network

  # Servicio Airflow
  airflow:
    build: 
      context: .
      dockerfile: Dockerfile-airflow
    image: apache/airflow:latest
    container_name: airflow
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_data:/opt/airflow
    command: webserver
    networks:
      - airflow-network

networks:
  spark-network:
  airflow-network:

volumes:
  airflow_data: