services:
  # Servicio MinIO
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./config/minio:/data
    command: server /data --console-address ":9001"
    networks:
      - shared-network

  # Servicio Spark Master
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile-spark
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8081:8080"
    environment:
      - SPARK_MODE=master
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - SPARK_WORKER_MEMORY=2g
      - SPARK_DRIVER_MEMORY=1g
      - SPARK_EXECUTOR_MEMORY=2g
      - EC2_PUBLIC_IP=${EC2_PUBLIC_IP}   # ✅ Pasamos la IP como variable de entorno
      # MINIO_ENDPOINT=http://${EC2_PUBLIC_IP}:9000
      - MINIO_ENDPOINT=http://minio:9000
    entrypoint: ["/bin/bash", "/opt/bitnami/scripts/spark/entrypoint-spark.sh", "master"]
    volumes:
      - spark_work:/opt/bitnami/spark/work  # ✅ Volumen compartido
      - ./scripts:/opt/airflow/scripts
    networks:
      - shared-network

  # Servicio Spark Worker
  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile-spark
    container_name: spark-worker
    user: "root"  # ✅ Ejecutar como root para evitar problemas de permisos
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - SPARK_WORKER_MEMORY=2g
      - EC2_PUBLIC_IP=${EC2_PUBLIC_IP}   # ✅ Pasamos la IP como variable de entorno
      - MINIO_ENDPOINT=http://minio:9000
    entrypoint: ["/bin/bash", "/opt/bitnami/scripts/spark/entrypoint-spark.sh", "worker"]
    volumes:
      - spark_work:/opt/bitnami/spark/work  # ✅ Montar volumen compartido
      - ./scripts:/opt/airflow/scripts
    networks:
      - shared-network

  # Base de Datos PostgreSQL para Airflow
  postgres:
    image: postgres:13
    container_name: airflow-db
    hostname: airflow-db
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_postgres:/var/lib/postgresql/data
      - ./scripts:/opt/airflow/scripts
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql:ro
    networks:
      - shared-network

  # Servicio Airflow Webserver
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile-airflow
    container_name: airflow-webserver
    restart: always
    ports:
      - "8082:8082"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW_HOME=/opt/airflow
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AIRFLOW__WEBSERVER__WEB_SERVER_HOST=0.0.0.0
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8082  # ✅ Configuración explícita
      - EC2_PUBLIC_IP=${EC2_PUBLIC_IP}  # 🔥 PASAMOS LA IP PÚBLICA
      - MINIO_ENDPOINT=http://minio:9000
    entrypoint: ["/bin/bash", "/opt/airflow/entrypoint.sh", "webserver"]
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_data:/opt/airflow
      - ./scripts:/opt/airflow/scripts
    networks:
      - shared-network

  # Servicio Airflow Scheduler
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile-airflow
    container_name: airflow-scheduler
    restart: always
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW_HOME=/opt/airflow
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - EC2_PUBLIC_IP=${EC2_PUBLIC_IP}  # 🔥 PASAMOS LA IP PÚBLICA
      - MINIO_ENDPOINT=http://minio:9000
    entrypoint: ["/bin/bash", "/opt/airflow/entrypoint.sh", "scheduler"]
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_data:/opt/airflow
      - ./scripts:/opt/airflow/scripts
    depends_on:
      - spark-master
      - postgres
    networks:
      - shared-network

  # Servicio Hive Metastore
  hive-metastore:
    image: starburstdata/hive:3.1.2-e.18  # Usamos la imagen oficial
    container_name: hive-metastore
    ports:
      - "9083:9083"  # Metastore Thrift
    environment:
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://postgres:5432/metastore
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_USER: airflow
      HIVE_METASTORE_PASSWORD: airflow
      HIVE_METASTORE_WAREHOUSE_DIR: s3://hudi-tables/
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: admin
      S3_SECRET_KEY: password
      S3_PATH_STYLE_ACCESS: "true"
      REGION: "us-east-1"
      HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
    depends_on:
      - postgres
      - minio
    volumes:
      - ./init-metastore.sh:/docker-entrypoint-initdb.d/init-metastore.sh:ro
      - ./config/hive/hive-site.xml:/opt/apache-hive-3.1.2-bin/conf/hive-site.xml:ro
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/init-metastore.sh"]
    networks:
      - shared-network

  # Servicio Trino
  trino-coordinator:
    build:
      context: .
      dockerfile: Dockerfile.trino
    container_name: trino-coordinator
    hostname: trino-coordinator
    ports:
      - "8083:8080"
    environment:
      - TRINO_NODE=trino-coordinator
      - TRINO_HTTP_PORT=8080
      - TRINO_HIVE_METASTORE_URI=thrift://hive-metastore:9083
    volumes:
      - ./trino/etc:/etc/trino
      - trino_data:/var/trino
      #- ./jars:/usr/lib/trino/plugin/hudi-trino-bundle
    networks:
      - shared-network
    depends_on:
      - hive-metastore
      - minio

networks:
  shared-network:
    driver: bridge

volumes:
  airflow_data:
  airflow_logs:
  airflow_postgres:
  spark_work:  # ✅ Volumen compartido para evitar problemas de permisos
  hive_metastore_postgresql:  # Para almacenamiento persistente de Hive
  trino_data:

